# numpy란?
* Numerical Python의 약자. 과학적, 산업적 연산을 위한 파이썬 패키지
* 다차원 배열, 행렬 연산에 주로 사용


In [ ]:
# !pip install numpy
# !conda install numpy

# 차원

* 0차원 = 점   ,      스칼라


* 1차원 = 선   ,      벡터
* 벡터는 방향을 가진 데이터

* 2차원 = 면, metrix, dataframe

* 3차원 = 공간, 입체

* 4차원 = 3차원 요소가 2개 이상

In [2]:
import numpy as np

In [5]:
a = np.array([1,2,3,4,5])

In [6]:
a

array([1, 2, 3, 4, 5])

In [7]:
a.ndim

1

In [9]:
b=32

In [10]:
b.ndim

AttributeError: 'int' object has no attribute 'ndim'

In [15]:
c = np.array([[1,2,3,4,5],[1,2,3,4,5]])
c

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [17]:
c.ndim

2

In [19]:
d= np.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]])
d

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [20]:
d.ndim

3

In [21]:
e=np.array([[[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]],[[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]]])
e

array([[[[1, 2, 3, 4, 5],
         [1, 2, 3, 4, 5]],

        [[1, 2, 3, 4, 5],
         [1, 2, 3, 4, 5]]],


       [[[1, 2, 3, 4, 5],
         [1, 2, 3, 4, 5]],

        [[1, 2, 3, 4, 5],
         [1, 2, 3, 4, 5]]]])

In [22]:
e.ndim

4

In [23]:
a.shape

(5,)

In [26]:
c.shape

(2, 5)

# numpy를 사용하는 이유: 행렬 연산이 쉽고 빠르기 때문

In [27]:
a = 10

In [28]:
scalar = a+1
scalar

11

* 벡터연산

In [31]:
b=np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [32]:
b=b+3
b

array([4, 5, 6, 7, 8])

In [ ]:
hap=[]
for num in b:
    hap.append(num+3)

In [34]:
c=[1,2,3,4,5]
c

[1, 2, 3, 4, 5]

In [35]:
c=c+3
c

TypeError: can only concatenate list (not "int") to list

In [36]:
b=b*2


In [37]:
b

array([ 8, 10, 12, 14, 16])

In [38]:
d=[[1,2,3],[1,2,3],[1,2,3]]
d

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [49]:
d=d+5

TypeError: can only concatenate list (not "int") to list

In [46]:
hap=[]
for i in d:
    temp=[]
    for j in i:
        temp.append(j+5)
    hap.append(temp)
hap

[[6, 7, 8], [6, 7, 8], [6, 7, 8]]

In [39]:
d2= np.array([[1,2,3],[1,2,3],[1,2,3]])
d2

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [48]:
d2=d2+5
d2

array([[6, 7, 8],
       [6, 7, 8],
       [6, 7, 8]])

# numpy에서 자주 사용하는 메서드
* .ndim: 몇 차원인지 보는 것
* .shape: 몇 차원, 몇 행 몇 열로 되어있는지 구조 확인
* .size: 배열 안에 있는 요소의 총 갯수가 몇개인지
* .dtype: 데이터 타입이 무엇인지
* .itemsize: 1개 자료의 크기는 몇 인지

In [50]:
d2.ndim

2

In [51]:
d2.shape

(3, 3)

In [52]:
d2.size

9

In [53]:
d2.dtype

dtype('int64')

In [54]:
d2.itemsize

8

In [55]:
d3=d2/2
d3


array([[3. , 3.5, 4. ],
       [3. , 3.5, 4. ],
       [3. , 3.5, 4. ]])

In [56]:
d3.dtype

dtype('float64')

# ndarray 만들기
* np.array(리스트/튜플)
* 자료형은 반드시 1가지만 넣는다.

In [60]:
e=np.array([1,2,3,4,5])
e.dtype

dtype('int64')

In [62]:
e2=np.array([1,2,3,4,5.3])
e2.dtype

dtype('float64')

In [63]:
e3=np.array([1,2,'3',4,5.3])
e3.dtype

dtype('<U32')

* np.arange(시작,끝+1,step)


In [64]:
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [65]:
np.arange(3,101,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

* reshape(행, 열) 벡터를 원하는 크기의 matrix로 변한

In [66]:
a=np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [70]:
a.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

* .flatten() 다차원 데이터를 1차원 배열로 바꿔주는 함수

In [71]:
a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

정해진 숫자 범위 안에서 균등하게 구간을 나눌 때
* np.linspace(시작,끝,구간수)

In [72]:
np.linspace(0,1,123)

array([0.        , 0.00819672, 0.01639344, 0.02459016, 0.03278689,
       0.04098361, 0.04918033, 0.05737705, 0.06557377, 0.07377049,
       0.08196721, 0.09016393, 0.09836066, 0.10655738, 0.1147541 ,
       0.12295082, 0.13114754, 0.13934426, 0.14754098, 0.1557377 ,
       0.16393443, 0.17213115, 0.18032787, 0.18852459, 0.19672131,
       0.20491803, 0.21311475, 0.22131148, 0.2295082 , 0.23770492,
       0.24590164, 0.25409836, 0.26229508, 0.2704918 , 0.27868852,
       0.28688525, 0.29508197, 0.30327869, 0.31147541, 0.31967213,
       0.32786885, 0.33606557, 0.3442623 , 0.35245902, 0.36065574,
       0.36885246, 0.37704918, 0.3852459 , 0.39344262, 0.40163934,
       0.40983607, 0.41803279, 0.42622951, 0.43442623, 0.44262295,
       0.45081967, 0.45901639, 0.46721311, 0.47540984, 0.48360656,
       0.49180328, 0.5       , 0.50819672, 0.51639344, 0.52459016,
       0.53278689, 0.54098361, 0.54918033, 0.55737705, 0.56557377,
       0.57377049, 0.58196721, 0.59016393, 0.59836066, 0.60655

* sort()를 쓰면 바뀐 내용이 저장되고, sorted()를 쓰면 저장되지 않는다.

## argsort() 자료중 값이 작은 것에서 큰 순으로 인덱스 출력


In [76]:
g=np.array([5,0.5,-7,42,10])
g


array([ 5. ,  0.5, -7. , 42. , 10. ])

In [75]:
g.argsort()

array([2, 1, 0, 3])

# 배열 합치기
* np.concatenate()

In [79]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


* np.concatenate((a,b)) 의 기본 병합 방향은 행방향, axis=0
* 행방향으로 합칠 때는 두 행렬의 열의 길이가 같아야 합쳐짐


In [82]:
np.concatenate((a,b))
np.concatenate((a,b)).shape

(4, 2)

* axis=1은 열방향으로 붙음
* 두 행렬의 행 길이가 같아야 붙음

In [83]:
np.concatenate((a,b), axis=1).shape

(2, 4)

## 벡터와 matrix는 합칠 수 없다


## 합치는 방향의 모양이 일치하지 않으면 합치기 X

In [3]:
c = np.array([[1,2],[3,4]])
d = np.array([[5,6]])
print(c)
print(c.shape)
print(c.ndim)
print(d)
print(d.shape)
print(d.ndim)

[[1 2]
 [3 4]]
(2, 2)
2
[[5 6]]
(1, 2)
2


In [4]:
concat_row2 = np.concatenate((c,d), axis=0)
print(concat_row2.shape)
print(concat_row2)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


## 전치 행렬 만들기
* .T
* .transpose()
* .reshape()



## 브로드 캐스팅
* 벡터와 스칼라, 또는 매트릭스와 벡터를 연산할 때 자동으로 행렬 크기를 맞춰 주는 것
 

In [6]:
a=np.arange(1,16).reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [7]:
a=a+3
a

array([[ 4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18]])

In [8]:
b = np.array([1,2,3,4,5])
print(a.shape)
print(b.shape)
a + b

(3, 5)
(5,)


array([[ 5,  7,  9, 11, 13],
       [10, 12, 14, 16, 18],
       [15, 17, 19, 21, 23]])

In [9]:
b = np.array([1,2,3,4,5])
print(a.shape)
print(b.shape)
c =  a + b

(3, 5)
(5,)


In [10]:
c[2][:3][::-1]

array([19, 17, 15])