In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [44]:
train_df = pd.read_csv("https://raw.githubusercontent.com/haram4th/ablearn/main/ratings_train.txt", sep='\t')

In [45]:
test_df = pd.read_csv("https://raw.githubusercontent.com/haram4th/ablearn/main/ratings_test.txt", sep='\t' )

In [46]:
train_df

id                                           document  label
0        9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1        3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2       10265843                                  너무재밓었다그래서보는것을추천한다      0
3        9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4        6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
...          ...                                                ...    ...
149995   6222902                                인간이 문제지.. 소는 뭔죄인가..      0
149996   8549745                                      평점이 너무 낮아서...      1
149997   9311800                    이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?      0
149998   2376369                        청춘 영화의 최고봉.방황과 우울했던 날들의 자화상      1
149999   9619869                           한국 영화 최초로 수간하는 내용이 담긴 영화      0

[150000 rows x 3 columns]

In [47]:
test_df

id                                           document  label
0      6270596                                                굳 ㅋ      1
1      9274899                               GDNTOPCLASSINTHECLUB      0
2      8544678             뭐야 이 평점들은.... 나쁘진 않지만 10점 짜리는 더더욱 아니잖아      0
3      6825595                   지루하지는 않은데 완전 막장임... 돈주고 보기에는....      0
4      6723715  3D만 아니었어도 별 다섯 개 줬을텐데.. 왜 3D로 나와서 제 심기를 불편하게 하죠??      0
...        ...                                                ...    ...
49995  4608761          오랜만에 평점 로긴했네ㅋㅋ 킹왕짱 쌈뽕한 영화를 만났습니다 강렬하게 육쾌함      1
49996  5308387       의지 박약들이나 하는거다 탈영은 일단 주인공 김대희 닮았고 이등병 찐따 OOOO      0
49997  9072549                 그림도 좋고 완성도도 높았지만... 보는 내내 불안하게 만든다      0
49998  5802125     절대 봐서는 안 될 영화.. 재미도 없고 기분만 잡치고.. 한 세트장에서 다 해먹네      0
49999  6070594                                         마무리는 또 왜이래      0

[50000 rows x 3 columns]

In [48]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype 
---  ------    --------------   ----- 
 0   id        150000 non-null  int64 
 1   document  149995 non-null  object
 2   label     150000 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 3.4+ MB


In [49]:
train_df.dropna(inplace=True)

In [50]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        50000 non-null  int64 
 1   document  49997 non-null  object
 2   label     50000 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 1.1+ MB


In [51]:
test_df.dropna(inplace=True)

In [52]:
print(train_df.info())
print(test_df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 149995 entries, 0 to 149999
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype 
---  ------    --------------   ----- 
 0   id        149995 non-null  int64 
 1   document  149995 non-null  object
 2   label     149995 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 4.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
Index: 49997 entries, 0 to 49999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        49997 non-null  int64 
 1   document  49997 non-null  object
 2   label     49997 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 1.5+ MB
None


In [53]:
train_df['document']

0                                       아 더빙.. 진짜 짜증나네요 목소리
1                         흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나
2                                         너무재밓었다그래서보는것을추천한다
3                             교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정
4         사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...
                                ...                        
149995                                  인간이 문제지.. 소는 뭔죄인가..
149996                                        평점이 너무 낮아서...
149997                      이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?
149998                          청춘 영화의 최고봉.방황과 우울했던 날들의 자화상
149999                             한국 영화 최초로 수간하는 내용이 담긴 영화
Name: document, Length: 149995, dtype: object

In [54]:
train_df['document'][0]

'아 더빙.. 진짜 짜증나네요 목소리'

In [55]:
train_df['document'][4].translate(str.maketrans('','','.'))

'사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 던스트가 너무나도 이뻐보였다'

In [56]:
import string

# 정규표현식 re
* import re
* pattern = r'[가-힣 0-9 a-z A-Z]+' 한글, 숫자, 영어 대소문자만 추출
* matches = re.findall(pattern, data)

In [57]:
import re

In [58]:
def text_clean(x):
    pattern = r'[가-힣 0-9 a-z A-Z]+'
    matches = re.findall(pattern, x)
    matches = "".join(matches)
    return matches

In [59]:
train_df['document'] = train_df['document'].apply(text_clean)

In [60]:
test_df['document'] = test_df['document'].apply(text_clean)

In [61]:
test_df['document']

0                                                   굳 
1                                 GDNTOPCLASSINTHECLUB
2                   뭐야 이 평점들은 나쁘진 않지만 10점 짜리는 더더욱 아니잖아
3                            지루하지는 않은데 완전 막장임 돈주고 보기에는
4        3D만 아니었어도 별 다섯 개 줬을텐데 왜 3D로 나와서 제 심기를 불편하게 하죠
                             ...                      
49995          오랜만에 평점 로긴했네 킹왕짱 쌈뽕한 영화를 만났습니다 강렬하게 육쾌함
49996     의지 박약들이나 하는거다 탈영은 일단 주인공 김대희 닮았고 이등병 찐따 OOOO
49997                  그림도 좋고 완성도도 높았지만 보는 내내 불안하게 만든다
49998       절대 봐서는 안 될 영화 재미도 없고 기분만 잡치고 한 세트장에서 다 해먹네
49999                                       마무리는 또 왜이래
Name: document, Length: 49997, dtype: object

In [62]:
test_df['document']

0                                                   굳 
1                                 GDNTOPCLASSINTHECLUB
2                   뭐야 이 평점들은 나쁘진 않지만 10점 짜리는 더더욱 아니잖아
3                            지루하지는 않은데 완전 막장임 돈주고 보기에는
4        3D만 아니었어도 별 다섯 개 줬을텐데 왜 3D로 나와서 제 심기를 불편하게 하죠
                             ...                      
49995          오랜만에 평점 로긴했네 킹왕짱 쌈뽕한 영화를 만났습니다 강렬하게 육쾌함
49996     의지 박약들이나 하는거다 탈영은 일단 주인공 김대희 닮았고 이등병 찐따 OOOO
49997                  그림도 좋고 완성도도 높았지만 보는 내내 불안하게 만든다
49998       절대 봐서는 안 될 영화 재미도 없고 기분만 잡치고 한 세트장에서 다 해먹네
49999                                       마무리는 또 왜이래
Name: document, Length: 49997, dtype: object

In [63]:
train_X=train_df['document']
test_X=test_df['document']

In [64]:
train_y=train_df['label']
test_y=test_df['label']

In [65]:
from sklearn.feature_extraction.text import CountVectorizer

In [66]:
cv = CountVectorizer()
train_X_cv=cv.fit_transform(train_X)
test_X_cv=cv.transform(test_X)


In [67]:
from sklearn.model_selection import train_test_split

In [68]:
X_train, X_test, y_train, y_test = train_test_split(train_X_cv,train_y, test_size=0.4,random_state=7)

In [69]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

In [70]:
mnb=MultinomialNB()
mnb.fit(X_train,y_train)
pred=mnb.predict(X_test)
print(accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

0.8102770092336411
              precision    recall  f1-score   support

           0       0.85      0.76      0.80     30158
           1       0.78      0.86      0.82     29840

    accuracy                           0.81     59998
   macro avg       0.81      0.81      0.81     59998
weighted avg       0.81      0.81      0.81     59998



In [71]:
test_pred = mnb.predict(test_X_cv)
print(accuracy_score(test_y, test_pred))
print(classification_report(test_y , test_pred))

0.8062483749024941
              precision    recall  f1-score   support

           0       0.79      0.82      0.81     24826
           1       0.82      0.79      0.80     25171

    accuracy                           0.81     49997
   macro avg       0.81      0.81      0.81     49997
weighted avg       0.81      0.81      0.81     49997



# Konlpy의 Mecab을 이용해 형태소 분리

In [72]:
from konlpy.tag import Mecab

In [73]:
mecab = Mecab()

In [74]:
def tokenizer(text):
    tokens=mecab.morphs(text)
    #print(tokens)
    return tokens

In [75]:
train_df['document'][4]

'사이몬페그의 익살스런 연기가 돋보였던 영화스파이더맨에서 늙어보이기만 했던 커스틴 던스트가 너무나도 이뻐보였다'

In [76]:
tokenizer(train_df['document'][4])

['사이몬페그',
 '의',
 '익살',
 '스런',
 '연기',
 '가',
 '돋보였',
 '던',
 '영화',
 '스파이더맨',
 '에서',
 '늙',
 '어',
 '보이',
 '기',
 '만',
 '했',
 '던',
 '커스틴',
 '던스트',
 '가',
 '너무나',
 '도',
 '이뻐',
 '보였',
 '다']

## countvectorizer 설명
* tokenizer:
설명: 텍스트 데이터를 단어(token) 단위로 나누는 역할을 합니다. tokenizer=tokenizer는 사용자가 정의한 tokenizer 함수를 사용한다는 의미입니다.
예시: 이 tokenizer가 형태소 분석기일 수 있으며, 한국어 데이터를 처리할 때 주로 사용됩니다. 형태소 분석기를 사용하면 문장을 형태소 단위로 분리하여 보다 세밀한 단어 처리 및 분석을 할 수 있습니다.
기본값: None일 경우, 기본적으로 CountVectorizer는 공백이나 기호를 기준으로 텍스트를 나누고, token_pattern='\b\w+\b'을 사용해 단어를 추출합니다.
* ngram_range=(1,2):
설명: ngram_range는 벡터화할 때 단어 단위의 범위를 지정합니다. (1,2)로 설정된 경우, 1-gram과 2-gram을 모두 포함합니다. 즉, 단일 단어와 단어 2개의 조합(예: "좋다", "영화 좋다")을 모두 벡터화에 포함합니다.
n-gram의 장점: 단어 간의 관계를 더 잘 반영할 수 있습니다. 예를 들어, "좋다"와 "영화 좋다"는 서로 다른 맥락에서 사용될 수 있으므로, 이를 별도로 처리할 수 있습니다.
예시: "이 영화는 정말 좋다"라는 문장이 있을 경우, ngram_range=(1,2)를 적용하면 다음과 같은 n-gram이 생성됩니다:
1-gram: ['이', '영화는', '정말', '좋다']
2-gram: ['이 영화는', '영화는 정말', '정말 좋다']
* min_df=3:
설명: min_df는 단어가 등장하는 최소 문서 수를 설정하는 하이퍼파라미터입니다. min_df=3은 단어가 최소 3개 이상의 문서에 등장해야 해당 단어를 벡터화 과정에 포함시키는 것을 의미합니다.
목적: 너무 드물게 등장하는 단어는 의미가 없거나, 오히려 성능을 저해할 수 있기 때문에 이를 제거하기 위해 사용합니다. 일반적으로 자주 등장하지 않는 단어는 데이터에 노이즈를 추가하는 경향이 있습니다.
예시: "사자성어" 같은 단어가 데이터셋 내에서 단 1~2회만 등장한다면, min_df=3으로 설정된 경우 이 단어는 벡터화에 포함되지 않습니다.
* max_df=0.9:
설명: max_df는 단어가 등장하는 문서 비율의 최대치를 설정하는 하이퍼파라미터입니다. max_df=0.9는 단어가 전체 문서의 90% 이하에서 등장할 때만 벡터화에 포함시킵니다. 즉, 너무 자주 등장하는 단어(예: 불용어)는 제외됩니다.
목적: 모든 문서에서 지나치게 자주 등장하는 단어(예: "이", "그리고" 등)는 의미를 거의 제공하지 않기 때문에 이를 제거하기 위해 사용됩니다. 이처럼 너무 빈번하게 등장하는 단어는 일반적으로 텍스트의 구분에 유용하지 않다고 여겨집니다.
예시: 만약 "영화"라는 단어가 거의 모든 문서에서 등장한다면, max_df=0.9로 설정된 경우 이 단어는 벡터화 과정에서 제외됩니다.

In [77]:
from sklearn.feature_extraction.text import CountVectorizer

In [78]:
cv = CountVectorizer(tokenizer=tokenizer, max_df=0.8, min_df=3, ngram_range=(1,2))
train_X_cv=cv.fit_transform(train_X)
test_X_cv=cv.transform(test_X)


/home/user/miniforge3/envs/nlp/lib/python3.10/site-packages/sklearn/feature_extraction/text.py:521: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [79]:
from sklearn.model_selection import train_test_split

In [80]:
X_train, X_test, y_train, y_test = train_test_split(train_X_cv,train_y, test_size=0.4,random_state=7)

In [81]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

In [82]:
mnb=MultinomialNB()
mnb.fit(X_train,y_train)
pred=mnb.predict(X_test)
print(accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

0.8577119237307911
              precision    recall  f1-score   support

           0       0.85      0.86      0.86     30158
           1       0.86      0.85      0.86     29840

    accuracy                           0.86     59998
   macro avg       0.86      0.86      0.86     59998
weighted avg       0.86      0.86      0.86     59998



In [83]:
test_pred = mnb.predict(test_X_cv)
print(accuracy_score(test_y, test_pred))
print(classification_report(test_y , test_pred))

0.8561313678820729
              precision    recall  f1-score   support

           0       0.85      0.87      0.86     24826
           1       0.86      0.85      0.86     25171

    accuracy                           0.86     49997
   macro avg       0.86      0.86      0.86     49997
weighted avg       0.86      0.86      0.86     49997



In [85]:
# 한글깨짐 방짐
#!pip install koreanize-matplotlib
import koreanize_matplotlib

# TfidfVectorizer : 단어의 중요도를 계산


2) TfidfVectorizer: TF-IDF (Term Frequency-Inverse Document Frequency) 기반 벡터화
작동 방식: TfidfVectorizer는 단어의 빈도뿐만 아니라, 단어의 중요도를 계산합니다. 여기서는 TF-IDF 값을 사용하여 문서 간 차별성을 강조합니다.
* TF (Term Frequency): 단어가 문서에서 얼마나 자주 등장했는지를 나타냅니다.
* IDF (Inverse Document Frequency): 단어가 다른 문서에 얼마나 자주 등장하지 않았는지를 나타냅니다. 자주 등장하지 않는 단어는 더 중요한 단어로 간주합니다.
* 특징: TF-IDF는 문서 전체에서 자주 등장하는 흔한 단어들(예: "그리고", "이다" 등)의 중요도를 낮추고, 문서에서만 중요한 단어들의 중요도를 높입니다.
단순히 빈도가 높은 단어보다 특정 문서에서 더 특징적인 단어에 더 높은 가중치를 부여합니다.
* 예시: 위의 문서 1과 문서 2에 대해 TfidfVectorizer로 변환하면, 공통 단어들(예: "있다", "고양이")의 중요도는 낮아지고, 차별적인 단어(예: "위에", "아래에")의 중요도는 상대적으로 높아집니다.

CountVectorizer와 TfidfVectorizer 비교
| 특성             | CountVectorizer                                     | TfidfVectorizer                                               |
|----------------------|--------------------------------------------------------|-------------------------------------------------------------------|
| 기반             | 단어의 단순 빈도                                        | 단어 빈도 + 문서 내에서의 상대적 중요도(TF-IDF)                     |
| 단어 빈도 계산    | 문서에서 등장한 단어의 단순한 등장 횟수를 셈            | 단어의 등장 횟수(TF)와 해당 단어가 문서들에서 얼마나 자주 등장하지 않았는지를 함께 고려(IDF) |
| 빈번한 단어 처리  | 문서에서 자주 등장하는 단어일수록 높은 가중치를 부여    | 문서에서 흔한 단어는 가중치를 낮추고, 드문 단어는 높은 가중치를 부여   |
| 주요 용도        | 단순한 단어 빈도 기반 분석이 필요할 때 사용             | 문서 간 차별적인 단어를 구별할 때 유용                                |
| 계산 비용         | 상대적으로 적음                                         | 상대적으로 더 복잡하고 계산 비용이 높음                                |

In [87]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [88]:
documents = ["고양이가 나무 위에 있다", "나무 아래에 고양이가 있다"]
c_vec = CountVectorizer()
sample = c_vec.fit_transform(documents)
print(c_vec.get_feature_names_out())
print(sample.toarray())


['고양이가' '나무' '아래에' '위에' '있다']
[[1 1 0 1 1]
 [1 1 1 0 1]]


In [89]:
documents = ["고양이가 나무 위에 있다", "나무 아래에 고양이가 있다"]
tfidf_vec = TfidfVectorizer()
sample = tfidf_vec.fit_transform(documents)
print(tfidf_vec.get_feature_names_out())
print(sample.toarray())


['고양이가' '나무' '아래에' '위에' '있다']
[[0.44832087 0.44832087 0.         0.63009934 0.44832087]
 [0.44832087 0.44832087 0.63009934 0.         0.44832087]]


In [92]:
tfidf_vec = TfidfVectorizer(tokenizer=tokenizer, max_df=0.8, min_df=3, ngram_range=(1,2))
train_X_cv=tfidf_vec.fit_transform(train_X)
test_X_cv=tfidf_vec.transform(test_X)


In [93]:
from sklearn.model_selection import train_test_split

In [94]:
X_train, X_test, y_train, y_test = train_test_split(train_X_cv,train_y, test_size=0.4,random_state=7)

In [95]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

In [96]:
mnb=MultinomialNB()
mnb.fit(X_train,y_train)
pred=mnb.predict(X_test)
print(accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

0.8608953631787726
              precision    recall  f1-score   support

           0       0.86      0.87      0.86     30158
           1       0.86      0.85      0.86     29840

    accuracy                           0.86     59998
   macro avg       0.86      0.86      0.86     59998
weighted avg       0.86      0.86      0.86     59998



In [97]:
test_pred = mnb.predict(test_X_cv)
print(accuracy_score(test_y, test_pred))
print(classification_report(test_y , test_pred))

0.8598915934956097
              precision    recall  f1-score   support

           0       0.85      0.87      0.86     24826
           1       0.87      0.85      0.86     25171

    accuracy                           0.86     49997
   macro avg       0.86      0.86      0.86     49997
weighted avg       0.86      0.86      0.86     49997

